services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app  # Bind mount the parent directory
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    command: ["poetry", "run", "pytest"]

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4572:4572"
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - localstack_data:/var/lib/localstack  # Use the named volume

  init-s3:
    image: amazonlinux
    depends_on:
      - localstack
    entrypoint: ["/bin/sh", "-c", "/scripts/create-bucket.sh"]
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ../bin/create-bucket.sh:/scripts/create-bucket.sh  # Bind mount the script

volumes:
  localstack_data:
